// GENERATED by scripts/gen-content-counts.ts — do not edit by hand.
//   npm run gen:counts              rewrite
//   npm run gen:counts -- --check   exit 1 when stale
//
// Numbers only: this module is imported by CheatSidebar (a client component in
// the hub layout), so anything else in here would ship on every route.
import type { TopicSlug } from './types'

export interface TopicCoverage {
  /** readState key prefixes owned by this sidebar row (always end in ':'). */
  prefixes: string[]
  /** Distinct trackable keys across those prefixes. */
  total: number
}

export const TOPIC_COVERAGE: Record<TopicSlug, TopicCoverage> = {
  "algorithms": { prefixes: ["algorithms:"], total: 4 },
  "leetcode": { prefixes: ["practice:"], total: 92 },
  "architecture": { prefixes: ["architecture:"], total: 19 },
  "fullstack": { prefixes: ["fullstack:"], total: 21 },
  "react": { prefixes: ["react:"], total: 43 },
  "react-native": { prefixes: ["react-native:"], total: 26 },
  "nextjs": { prefixes: ["nextjs:"], total: 9 },
  "angular": { prefixes: ["angular:"], total: 32 },
  "javascript": { prefixes: ["javascript:"], total: 27 },
  "git": { prefixes: ["git:"], total: 15 },
  "ai": { prefixes: ["ai:"], total: 14 },
  "ide": { prefixes: ["ide:"], total: 6 },
  "quickref": { prefixes: ["quickref:react:", "quickref:javascript:", "quickref:angular:", "quickref:nextjs:", "quickref:leetcode:", "quickref:architecture:", "quickref:fullstack:", "quickref:git:", "quickref:ai:"], total: 134 },
}
