// Generates src/lib/cheatsheet/contentCounts.generated.ts — the per-topic
// denominators behind the sidebar progress bars.
//
// WHY A GENERATED FILE: CheatSidebar is a client component in the hub layout,
// so everything it imports ships on every route. The counts live inside the
// content modules (~20k lines of HTML-in-strings across react.ts, angular.ts,
// javascript.ts, …). Importing those from the sidebar would drag the whole
// content tree into the shared client bundle. This emits numbers only.
//
//   npm run gen:counts              rewrite the file
//   npm run gen:counts -- --check   exit 1 if it is stale
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { reactContent } from '../src/lib/cheatsheet/react'
import { angularContent } from '../src/lib/cheatsheet/angular'
import { javascriptContent, javascriptLinks } from '../src/lib/cheatsheet/javascript'
import { nextjsContent } from '../src/lib/cheatsheet/nextjs'
import { reactNativeContent } from '../src/lib/cheatsheet/react-native'
import { fullstackContent } from '../src/lib/cheatsheet/fullstack'
import { architectureContent } from '../src/lib/cheatsheet/architecture'
import { gitContent } from '../src/lib/cheatsheet/git'
import { aiContent } from '../src/lib/cheatsheet/ai'
import { ideContent } from '../src/lib/cheatsheet/ide'
import { algorithmsContent } from '../src/lib/cheatsheet/algorithms'
import { practiceTasks } from '../src/lib/cheatsheet/practiceTasks'
import { QUICKREF_BLOCKS } from '../src/lib/cheatsheet/quickref'
import { quickRefBlockKeys } from '../src/lib/cheatsheet/quickrefKeys'
import { TOPICS } from '../src/lib/cheatsheet/registry'
import type { TopicContent, TopicSlug } from '../src/lib/cheatsheet/types'

const OUT = resolve('src/lib/cheatsheet/contentCounts.generated.ts')
const check = process.argv.includes('--check')

// Sidebar slug (== readState namespace) → the TopicContent exports rendered
// under it. `javascript` is listed twice on purpose: ProseTopicView keys both
// /javascript and /javascript/links as `${content.slug}:${id}`, so the two
// pages share one namespace and one denominator.
const PROSE: Partial<Record<TopicSlug, TopicContent[]>> = {
  algorithms: [algorithmsContent],
  architecture: [architectureContent],
  fullstack: [fullstackContent],
  react: [reactContent],
  'react-native': [reactNativeContent],
  nextjs: [nextjsContent],
  angular: [angularContent],
  javascript: [javascriptContent, javascriptLinks],
  git: [gitContent],
  ai: [aiContent],
  ide: [ideContent],
}

// Keys are derived exactly as the views derive them, so numerator and
// denominator can never drift:
//   prose     ProseTopicView       `${content.slug}:${section.id}`
//   practice  PracticeTasksView    `practice:${task.id}`
//   quickref  QuickRefTopicView    `quickref:${slug}:${blockKey}`
function collect(): Record<TopicSlug, { prefixes: string[]; keys: Set<string> }> {
  const out = {} as Record<TopicSlug, { prefixes: string[]; keys: Set<string> }>

  for (const [slug, contents] of Object.entries(PROSE) as [TopicSlug, TopicContent[]][]) {
    const keys = new Set<string>()
    for (const content of contents) {
      for (const section of content.sections) keys.add(`${slug}:${section.id}`)
    }
    out[slug] = { prefixes: [`${slug}:`], keys }
  }

  // 🧩 Практика tracks practice tasks. LeetCode problems live in
  // UserData.progress ('solved' | 'attempted') — a different state model, so
  // they deliberately do not feed this bar.
  out.leetcode = {
    prefixes: ['practice:'],
    keys: new Set(practiceTasks.map((t) => `practice:${t.id}`)),
  }

  // ⚡ Шпаргалка is an umbrella over 9 boards, each with its own prefix.
  const quickrefKeys = new Set<string>()
  const quickrefPrefixes: string[] = []
  for (const [slug, blocks] of Object.entries(QUICKREF_BLOCKS)) {
    if (!blocks) continue
    quickrefPrefixes.push(`quickref:${slug}:`)
    quickRefBlockKeys(blocks).forEach((k) => quickrefKeys.add(`quickref:${slug}:${k}`))
  }
  out.quickref = { prefixes: quickrefPrefixes, keys: quickrefKeys }

  return out
}

const collected = collect()

// A topic added to registry.ts with no coverage entry would render a permanent
// 0% bar — fail loudly instead.
const missing = TOPICS.filter((t) => !collected[t.slug])
if (missing.length) {
  throw new Error(`No content counted for: ${missing.map((t) => t.slug).join(', ')}`)
}

const rows = TOPICS.map((topic) => {
  const { prefixes, keys } = collected[topic.slug]
  return { slug: topic.slug, prefixes, total: keys.size }
})

const body = rows
  .map(
    (r) =>
      `  ${JSON.stringify(r.slug)}: { prefixes: [${r.prefixes
        .map((p) => JSON.stringify(p))
        .join(', ')}], total: ${r.total} },`,
  )
  .join('\n')

const file = `// GENERATED by scripts/gen-content-counts.ts — do not edit by hand.
//   npm run gen:counts              rewrite
//   npm run gen:counts -- --check   exit 1 when stale
//
// Numbers only: this module is imported by CheatSidebar (a client component in
// the hub layout), so anything else in here would ship on every route.
import type { TopicSlug } from './types'

export interface TopicCoverage {
  /** readState key prefixes owned by this sidebar row (always end in ':'). */
  prefixes: string[]
  /** Distinct trackable keys across those prefixes. */
  total: number
}

export const TOPIC_COVERAGE: Record<TopicSlug, TopicCoverage> = {
${body}
}
`

if (check) {
  const current = readFileSync(OUT, 'utf8')
  if (current !== file) {
    console.error('✗ contentCounts.generated.ts is stale — run: npm run gen:counts')
    rows.forEach((r) => console.error(`   ${r.slug.padEnd(14)} ${r.total}`))
    process.exit(1)
  }
  console.log('✓ contentCounts.generated.ts is up to date')
} else {
  writeFileSync(OUT, file)
  console.log(`→ ${OUT}`)
}

rows.forEach((r) => console.log(`  ${r.slug.padEnd(14)} ${String(r.total).padStart(4)}`))
console.log(`  ${'РАЗОМ'.padEnd(14)} ${String(rows.reduce((n, r) => n + r.total, 0)).padStart(4)}`)
